### ISSUE TITLE
[Suggestion] Clicking the hide button on a hidden note unhides it

### ISSUE THREAD

**Issue by Lottiotta** [JKershaw/Noiys#10]
At the moment if I want to unhide a single note I have to delete cookies for Noiys.com and unhide *all* notes, thus having to view some really horrible stuff. (There is at least one troll hanging out on Noiys right now; it's not fun.)

So maybe there is a better solution, but this is a way it could be done: Clicking the hide button on a hidden note unhides it.

**Comment by JKershaw** [comment]
There's now an unhide link.

**Comment by Lottiotta** [comment]
Thanks! :)
