### ISSUE TITLE
Note isn't unhiding

### ISSUE THREAD

**Issue by Lottiotta** [JKershaw/Noiys#13]
It's this one: @55230b29d4259003009f6d12 http://www.noiys.com/status/55230b29d4259003009f6d12

It was posted 11 hours ago.

**Comment by JKershaw** [comment]
I can't reproduce the issue. I hid it on the Home feed, then unhid it, then reloaded the page, and all was fine.

**Comment by Lottiotta** [comment]
I just tried it on another note in a similar thingy (first note in a long conversation that you have to expand), and it unhid! So, I have no idea. :) Sorry!
