### ISSUE TITLE
Clicking on the permalink chainlink icon leads to an error page

### ISSUE THREAD

**Issue by Cassolotl** [JKershaw/Noiys#17]
Page title: Error

Text on page: Internal Server Error

To replicate: Go to noiys.com, click on the chainlink icon of any post, observe the error page, watch romcoms to feel better.

(Also I checked that I wasn't trying to view a post that had expired, it was a page freshly loaded so all the notes were recent.)

**Comment by JKershaw** [comment]
Fixed :)

**Comment by Cassolotl** [comment]
YEAHHHHH thanks! :D
