### ISSUE TITLE
How to create site same noiys.com

### ISSUE THREAD

**Issue by nguyentrongtanhlu** [JKershaw/Noiys#19]
Hi, 
Can you guides create my blog same noiys.com.

I want used wordpess??? or platform???

Please help me

**Comment by JKershaw** [comment]
You need to know a bit about coding to make your own version.

To have your own you need to:
* Make a copy of all the code (clone the git repository)
* Host it somewhere (e.g. upload it to Heroku)
* Set up the database (e.g. sign up to MongoDb's free tier and update the connection string variable)

**Comment by nguyentrongtanhlu** [comment]
hi,
help me create and set up one site  the same it

Vào 0:00, Th 3, 8 thg 8, 2023 John Kershaw ***@***.***> đã
viết:

**Comment by JKershaw** [comment]
If you don't know how to get code to run, then I don't think you'll be able to set this up I'm afraid.

If you can learn how to run NodeJs code on Heroku using git, then you'll be able to do it.

**Comment by nguyentrongtanhlu** [comment]
Hi
Do you know any plugin/tools to do the same on wordpress?

Vào Th 3, 8 thg 8, 2023 vào lúc 00:19 John Kershaw <
***@***.***> đã viết:

**Comment by JKershaw** [comment]
That's not something I've any experience with.

**Comment by nguyentrongtanhlu** [comment]
Ok, thanks for the reply.

Vào Th 4, 9 thg 8, 2023 vào lúc 19:03 John Kershaw <
***@***.***> đã viết:
