### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Salm0nsnak3** [JKershaw/Noiys#20]
Noiys.com displays an error message 

"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail"
![b6576094-29f8-4732-82ad-a1bebe34d88f](https://github.com/JKershaw/Noiys/assets/90401179/979a0533-8255-4977-9570-26cfa2615548)

**Comment by JKershaw** [comment]
Unfortunately the site broke due to some outdated code, and I've not had time to sort it out yet.

**Comment by JKershaw** [comment]
The issue has been fixed and the site is working again.
