### ISSUE TITLE
"Application error"

### ISSUE THREAD

**Issue by Cassolotl** [JKershaw/Noiys#21]
Alas!

https://www.noiys.com

>Application error
>An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
>heroku logs --tail

**Comment by JKershaw** [comment]
To be honest I don't know what broke, but it seems to have fixed itself.

Because everything gets deleted after 24 hours I'm not sure what caused the outage. If it happens again I'll take a proper look.

**Comment by JKershaw** [comment]
Closing this Issue as the site is online again.

**Comment by Cassolotl** [comment]
Haha, glad it didn't require any work on your part! :D Thanks!

**Comment by Cassolotl** [comment]
Oh I just remembered something - right before it started crashing out, there was one person (I think it was one person) where all their notes were in rainbow, even though they weren't using the #rainbow hashtag. Is that related?

**Comment by JKershaw** [comment]
Ah probably. If they were putting all kinds of weird or hidden text in, I
can imagine that causing the code to panic or break.

That would also explain why it fixed itself too.

Hopefully they come back and try it again, so it breaks when I'm watching
and I can fix it 😁

**Comment by Cassolotl** [comment]
Intriguing! :) I'll try and get screenshots or something next time. :D
