### ISSUE TITLE
Tabs have gone weird?

### ISSUE THREAD

**Issue by Cassolotl** [JKershaw/Noiys#22]
For the last couple of days I've seen people mentioning that their Noiys experience has been quite glitchy. One person said that their Home tab was totally empty, and my "Mine" tab has a lot of notes that I didn't write. Sometimes when I reload the "Mine" tab is empty.

When I click the "Home" tab, it says "Just loading your home feed now." and then nothing happens. And then if I click over onto a different tab, the "Just loading your home feed now." message stays there even though I'm on a different tab and there's messages underneath.

There was a recent update to a new version of something, I think - maybe it was that?

**Comment by JKershaw** [comment]
These sound exactly like the kind of bugs I'd introduce by fixing the code in the way that I did. The bugs I can replicate happen with the "Mine" tab, but I suspect there will be a few.

I'll take a look at the code when I can. If you (or anyone) find a way to reliably replicate the bug, please let me know as that makes it really easy to fix.

**Comment by Cassolotl** [comment]
> If you (or anyone) find a way to reliably replicate the bug, please let me know as that makes it really easy to fix.

So, if I haven't posted *anything* in the last 24 hours, the "Mine" tab is empty. And if I post one thing, and then click the "Mine" tab, it just becomes a duplicate of the "Recent" tab.

As far as I can tell, the "Home" tab just gets stuck on "Just loading your home feed now." without me having to do anything special.

The star/fave tab seems to be behaving as expected!

This was all in Chrome on a Mac.

**Comment by Cassolotl** [comment]
Okay, Home seems to be loading normally now...!

**Comment by Cassolotl** [comment]
ALSO, the thing with the Mine tab works like this:

1. Load page for the first time.
2. Click "Mine". Tab is empty.
3. Click "Recent".
4. Type note and submit.
5. Click "Mine". Tab shows most recent posts in time descending order.
6. Reload page.
7. "Mine" tab is unexpectedly empty.

(Chrome, Mac)

**Comment by Cassolotl** [comment]
Just spotted on Noiys that you fixed this! ❤️ Thank you for all your hard work today!
