### ISSUE TITLE
Ability to hide a note

### ISSUE THREAD

**Issue by JKershaw** [JKershaw/Noiys#4]
Perhaps using the keyword NO, hide a note. 

Hidden status saved locally, possibly also with a counter akin to verbs on the note itself. Client has ability to set a threshold to auto hide. And display hide count (feeding the trolls?)

**Comment by Lottiotta** [comment]
There's a bounty on it: https://www.bountysource.com/issues/7191232-ability-to-hide-a-note

**Comment by JKershaw** [comment]
Hide button exists. Saves client side. Allows a single note to be hidden forever.
