### ISSUE TITLE
Noiys Savior

### ISSUE THREAD

**Issue by Lottiotta** [JKershaw/Noiys#6]
A thing like [Tumblr Savior](http://bjornstar.com/tumblr-savior) but for Noiys would be amazing. You could tell it to automatically hide posts on Noiys with particular words or phrases in.

But I don't know if this would be part of Noiys or a third-party thing, and so I am not sure if I am posting this in the right place. Please feel free to mod it away if I'm doing it wrong. :)

**Comment by JKershaw** [comment]
Not sure how well it'd work in Noiys as there isn't really any good way to remember your preferences. If you don't mind re-entering your preferences every now and again, that could work.

**Comment by Lottiotta** [comment]
It sounds like it'd be more suited to a third-party browser extension mabobbin like Tumblr Savior or X-Kit, then?

**Comment by JKershaw** [comment]
Closing the issue. If there's specific features that are super-important, they can be made their own Issues.
